---
title: "Appendix A"
---

## SURPAS (Stanford Postdoc Association) By-Laws

*Postdocs at Stanford have been self-organized to represent their interests within the university community since at least 1998. SURPAS is governed by the following bylaws. SURPAS Council periodically votes on bylaws amendments to reflect changing needs of the organization and community; this process ensures new Council members are aware of our governing structure.*

--

## Bylaws of the Stanford University Postdoctoral Association

### History

The Stanford University Postdoctoral Association (SURPAS) was founded in 1998 to promote a community among Postdoctoral Scholars at Stanford University. SURPAS is governed by the Council. The Council was formed in Spring of 1999, and addresses issues related to Postdoctoral Scholars at Stanford. The Council functions in advocacy and helps to maintain a social structure within the postdoctoral community.

**Note:** The Stanford University Postdoctoral Association previously used the acronym SUPD, which was often confused with the Stanford University Police Department. In 2013, the Council appointed a Name and Logo committee to report on the name confusion and potential alternatives. The committee reported that even though the Stanford Police department uses the acronym SUDPS, or Stanford University Department of Public Safety, confusion still occurs, and many alternative acronyms were already claimed by other organizations at Stanford. For instance, SUPA was already used by the Stanford Undergraduate Psychology Association. The acronym SURPAS was identified as a viable alternative, which sounds like the word, “surpass” and has a meaning that aligns well with the mission of the Association. The council voted by majority on September 25, 2013, to adopt the acronym SURPAS.

### Revision History (current version approved: January 2023)
#### Section 1: 1998-1999 Session
A.  Creation

B.  1,200 Postdoctoral Scholars at Stanford

--

#### Section 2: 2010 Session

A.  Unknown

B.  1,800 Postdoctoral Scholars at Stanford

--

#### Section 3: 2013 Session

A.  Redesign of Bylaws based on Associated Students of Stanford University (ASSU) Bylaws

B.  Creation of Advisory Board

C.  Added articles for Conflict of Interest, Conflict Resolution, non-discrimination, decision making

D.  Removed redundant passages

E.  2,000 Postdoctoral Scholars at Stanford

--

#### Section 4: 2015 Session

A.  Added activity requirement for Council members to contribute to SURPAS that will be evaluated during review prior to re-election after one year

--

#### Section 5: 2016 Session

A.  Change in the election timing of co-chairs, leadership team and honorary committees

B.  Added a responsibility for secretary

C.  Added a clause on maternity leave

--

#### Section 6: 2017 Session
A.  Added positions of Events Coordinator and Advocacy Coordinator to leadership team

B.  Updated bylaws to reflect organizational practices (including cap on council seats, number of meetings held, SPIF budget, committee formation, officer responsibilities, timing of elections)

C.  Included diversity and inclusion statement in mission

D.  Expanded maternity leave clause to include other types of leave

E.  Added guidelines for external communications

F.  2,100 Postdoctoral Scholars at Stanford

--

#### Section 7: 2018 & 2019 Sessions
**Documentation of previously-approved updates**

A.  Use of poll everywhere for voting

B.  Nov and Dec meetings may occur earlier than the last week of month

C.  Council meetings can occur in different locations across campus

D.  SURPAS seats on ‘honorary committees’

E.  Updated structure and responsibilities for SURPAS Leadership

F.  Updated timing of elections to reflect offset co-chair positions and campaign regulations.

G.  Term information for Council and Leadership members

**Minor updates to bylaw language**

H.  Council member responsibilities include the ability to override decisions by the leadership team and require active participation in SURPAS activities 

I.  Council member term expiration includes notice

J.	Defined ‘adequate’ notification for meetings.

K.  Updated the process for the management of Committees and information stream from Committees to the Leadership and Council

L.  Recognition of other postdoc groups on campus

**Category 3 - Major updates to bylaw content**

M.  Votes of no confidence for removal from positions.

N.  Updated the process for the appointment and responsibilities of Committee chairs.

O.  Added new Community Engagement Liaison position

--

#### Section 8: 2020 Session
**Approved changes**

A.  Postdocs transitioning to non-tenure track roles may continue to be SURPAS members and occupy voting council member seats as long as there are open Council seats and no new members wishing to occupy these.

B.  Wording to increase accessibility to SURPAS Council Meetings

C.  Changes to guidelines for using SURPAS emails

**Minor updates to bylaw language**

D.  “Maternal/baby/bonding leave” changed to “parental/baby bonding leave”

E.  2400 postdocs at Stanford

--

#### Section 9: 2021-2022 Session

A.  SURPAS co-chairs should extend an invitation and share OPA meeting agenda to the affinity groups. This will enhance SURPAS collaborative interaction with the postdoc affinity groups.

B.  The position of SURPAS representative to the School of Medicine Diversity Cabinet is an elected position from within the current SURPAS leadership OR The position of SURPAS representative to the School of Medicine Diversity Cabinet is an elected position from within the SURPAS Council OR The position of SURPAS representative to the School of Medicine Diversity Cabinet will be assumed by the Advocacy Coordinator.

C.  SURPAS co-chairs should invite Faculty Staff Help Center to present at Council Meetings biannually – this is essential as postdocs are a transient community within Stanford and ensuring that all incoming postdocs have the opportunity to know about the services that FSHC provide is important. Postdocs face many challenges both in research, mentor-mentee relationships and personally and it is important to ensure that our community is aware of these services.

--

#### Section 10: 2022-2023 Session

A.  Addition to Treasurer/Financial Officer’s responsibility: All monthly financial transactions shall be completed within SURPAS for each month prior to the 1st of the next month.

B.  Addition to Co-Chairs’ responsibility: Add “Co-Chairs should schedule quarterly meetings with OPA and Affinity group co-chairs”.

C.  Council member responsibility: Council members must attend at least 9 (75%) council meetings in a year of service on council. Excused absences should be coordinated with the Operations Manager in advance of the meeting. Excused absences and canceled meetings will not be considered missed meetings. Council members missing 3 (25%) scheduled council meetings will be given a warning. Missing additional meetings thereafter will result in being removed from the roster and losing membership.

---

### Article I: General

#### Section 1: Mission

A.  The mission of the Stanford University Postdoctoral Association is to enrich the Postdoctoral experience at Stanford, to enable Postdoctoral Scholars to explore opportunities, and to empower Postdoctoral Scholars to become leaders in areas of their choice.

B.  The Council represents and advocates for the best interests of all Stanford Postdoctoral Scholars. Primary goals of the Council include the following:

    1. To develop social and networking opportunities for Postdoctoral Scholars from all disciplines, in the interest of fostering a community of postdocs at Stanford.

    2. To promote inclusion and representation of all postdoctoral fellows and advocate for a postdoctoral community that better reflects the diversity that is crucial for research and other progress.

    3. To work with University Administration to optimize the postdoctoral experience.

    4. To strive for the professional enrichment and development of Postdoctoral Scholars.

    5. To ensure that postdoctoral benefits and salaries are commensurate with the NIH salary scale and the high cost of living in the Bay Area.

    6. To clearly define and communicate the Postdoctoral Scholar status at an institutional level.

C.  The members of the Council will act as a liaison to the postdoctoral population at large and represent the interests of Postdoctoral Scholars to the Office of Postdoctoral Affairs and to Stanford University by representing Postdoctoral Scholars on University committees and governing bodies.

--

#### Section 2: Membership of Registered Postdoctoral Scholars

All registered Postdoctoral Scholars of Stanford University are members of SURPAS. Registered Postdoctoral Scholars of Stanford University shall be defined to include all Postdoctoral Scholars appointed by the Office of Postdoctoral Affairs of Stanford University. SURPAS recognizes that there are people working in similar positions [individuals who possess a doctoral degree (Ph.D., M.D., J.D., Ed.D., etc.) and conduct research under a Stanford faculty member's sponsorship or supervision, but are not appointed by the Office of Postdoctoral Affairs (such as Research Associates and Visiting Scholars)]. These individuals are not members of SURPAS, but are invited to participate in SURPAS events. SURPAS recognizes that Postdoctoral scholars may move into other non-tenure track trainee roles at Stanford upon expiration of the Postdoctoral scholar term limit or award of transitional funding. These former Postdocs may continue to be SURPAS members.

--

#### Section 3: Dissolution of the Organization.

SURPAS will be dissolved when its mission is accomplished.

--

#### Section 4: Non-Discrimination and Diversity Statement

These Bylaws, the Council, the elected officers, and all Committees, shall not discriminate against any individual or organization on account of race, gender, religion, ethnicity, nationality, sexual orientation, or physical or mental disability. SURPAS seeks to promote diversity and ensure equal opportunity and inclusion for all Postdoctoral Scholars, across all seven schools, in the membership, leadership, and activities of SURPAS. 

--

#### Section 5: Conflict of Interest

A.  The members of the Leadership Team, Council, and Committees are expected to avoid any actual or apparent conflict between their own individual personal or professional interests and the interests of SURPAS. The members of the Leadership Team, Council, and Committees shall act at all times in the best interests of SURPAS. This means setting aside personal self-interest and performing their duties in transaction of the affairs of SURPAS in such a manner that promotes confidence and trust in the integrity, objectivity and impartiality of the Leadership Team, the Council, and Committees.

B.  This Conflict of Interest policy is in place to protect both the individual and SURPAS from accusations of improper conduct. As such, all members of the Leadership Team, the Council, and Committees are expected to respect the Conflict of Interest policy and should feel personal responsibility for self-monitoring.

---

### Article II: Legislative Branch

#### Section 1: Members of the Council

A.  SURPAS Council shall be composed of thirty (30) total seats.

B.   All members of SURPAS are eligible to run for vacant Council seats. Former Postdocs who have moved into non-tenure track roles may continue to serve on SURPAS Council.

C.   If the Council has more volunteers than open slots, new members will be recruited by elections with consideration given to the current needs of the Council.

D.  If all Council member slots become full, Council slots occupied by former Postdocs now in early career, non-tenure track roles must move into advisory roles to make Council seats available for new members.

E.   The membership of the Council is to be representative of the Postdoctoral Scholar distribution across the seven schools at Stanford. This will be achieved to the extent possible, by active recruitment by current council members and the leadership team.

--

#### Section 2: Responsibilities

A.  The Council holds the overall responsibility for SURPAS’ operations with guidance from, the Leadership Team ([Article III, Section 1](#article-iii-executive-branch)), its Advisory Board ([Article VII, Section 2](#article-vii-review-and-conflict-resolution)), and the Office of Postdoctoral Affairs. Council members have the right to openly discuss decisions made by the Leadership Team and request a motion to override such decisions with a simple majority vote.

B.  Council members must attend at least 9 (75%) council meetings in a year of service on council. Excused absences should be coordinated with the **Operations Manager** in advance of the meeting. Excused absences and canceled meetings will not be considered missed meetings. Council members missing 3 (25%) scheduled council meetings will be given a warning. Missing additional meetings thereafter will result in being removed from the roster and losing membership.

C.  In addition to attending council meetings, council members must significantly contribute to SURPAS activities and the well-being of postdocs at Stanford. For example, council members are required to either (a) serve on the leadership team (Article III), (b) serve as a Faculty Senate representative (Section 7), (c) be an active member of a SURPAS Committee (Sections 5 & 6) or (d) be an active member of a postdoc affinity group. The council will review each member’s contribution to SURPAS and the well-being of postdocs at Stanford at the end of their one year term and can then vote on re-election to the SURPAS council.

D.  Council members must ensure that pertinent information is disseminated to the postdoctoral population at large. They will communicate concerns to the Council from those Postdoctoral Scholars that they represent, and hold informal meetings with Postdoctoral Scholars as necessary.

E.  Council members must inform Postdoctoral Scholars of special events and help organize as needed.

--

#### Section 3: Term Expiration

A.  Appointments to the Council are for one year, confirmed by a letter of appointment or email.

B.  Members who are no longer able to execute their tasks shall notify the **Co-Chairs** in writing.

C.  If a member fails to attend 3 meetings in a row, without prior notification to the **Operations Manager**, he or she will be notified in writing by the **Co-Chairs** that they are no longer an active member of the Council.

--

#### Section 4: Meetings of the Council

A.  The **Co-Chairs** and the Leadership Team may call meetings of the Council. Adequate public notice of meeting location and agenda items (defined as 3 business days) must be given for each meeting.

B.  Quorum for Council meetings shall consist of at least half of the non-vacant seats. If a quorum is not present, following reasonable notification for a second meeting, proposed motions may be voted upon with fewer members than a full quorum attending.

C.  Votes that concern SURPAS members will be done by Council members anonymously using paper voting slips or an online voting system, such as PollEverywhere. Council members can abstain from voting. Votes that concern missions, plans, and other impersonal items can be done by a show of hands, as the Council sees fit.

D.  The **Co-Chairs** shall share responsibility of the Presiding Officer at each Council meeting.

E.  Council meetings shall be scheduled the last week of each month, with the exception of November and December which may occur earlier in the month due to holidays. Additional Council meetings can be called, as the need arises. The Council shall be given adequate notice of planned meetings.

F.  Council meetings shall take place throughout campus and/or on zoom to ease accessibility and improve participation from postdocs across all Stanford schools and departments.

    1.  SURPAS Leadership members must actively be mindful of accessibility when scheduling Council meetings. This includes scheduling Council meetings in rooms that meet ADA requirements and which are located throughout campus, and/or via a web based platform (such as Zoom)

    2.  All SURPAS members are invited to attend meetings, but are eligible to vote only when they are members of the Council.

    3.  Council meetings last no longer than 1.5 hours. Unfinished business will be relegated to the next meeting.

G.  Order of Business

    1.  Agendas and supporting documents will be distributed in advance of all scheduled meetings.

    2.  Determination of quorum by the **Co-Chairs** and/or the ****Operations Manager****

    3.  Approval of previous Council meeting minutes by the Council, should there be comments on the draft.

    4.  Reports of special representatives and standing committees.

    5.  General orders or unfinished business.

    6.  Voting motions shall carry if they receive a majority vote.

    7.  Additional agenda items can be recommended to the **Co-Chairs** by any SURPAS member up to one day before the meeting.

--

#### Section 5: Committees

The Council shall have the power to create Committees for specific purposes, to vest in them all appropriate powers of the Council, and to determine their composition.

A.  Committees shall be composed of volunteers from the Council and SURPAS. It is recommended that all committees have at least one council member involved. Committee members shall appoint or elect a chair (or co-chairs) to manage the Committee. This chair or co-chairs must be approved by simple majority vote (anonymous or show of hands) of the Council.

B.  The duties of a Committee and its power to act on certain decisions shall be outlined at its formation and shall be approved by the Council. Leadership, on behalf of Council, will assist committees in carrying out their duties whenever possible and deemed appropriate.

C.  The Council will retain final responsibility for the committee’s actions and decisions. The members of the Committee and the Council have the power to remove a Committee Chair (or **Co-Chairs**) if necessary by a simple majority vote.

D.  Committees will submit a plan of action and a budget proposal to the **Treasurer/Financial Officer**, who will review it and present it to the Council. The Council can also decide to allocate a budget upon installment of a Committee, pending approval by the **Treasurer/Financial Officer**.

E.  All Committees shall regularly report to the Leadership Team, and, if suitable to the Council, at a Council meeting through the Chair (or **Co-Chairs**) or Committee Representative. The Committee Chair (or **Co-Chairs**) must submit a Project Plan outlining the Committee’s goals and activities for the year to the Leadership Team each January. Status reports from Committees may also be requested on an ad hoc basis by any Council member. If a Committee Chair or Representative is not a member of council, they will still be regulated under the same attendance requirements as Council members ([Article II Section 2](#article-ii-legislative-branch)).

F.  A Committee will go out of existence when its goals have been met or task is complete, or can be terminated or merged with another Committee by majority vote of the Council.

G.  Committees of structural importance or that serve essential roles to postdoc well-being at Stanford will become standing committees with their own guidelines.

H.  Any SURPAS member may propose a Committee to the **Co-Chairs**, Leadership, or Council. The Council will then discuss and vote on the formation of the Committee at the next meeting. Committees can be created by the Leadership without a vote of the Council ([Article III Section 1D](#article-iii-executive-branch)).

--

#### Section 6: Standing Committees - SURPAS Postdoc Initiative Fund (SPIF) 

A.  Objectives and mandate of SPIF: to provide financial support and foster Postdoctoral Scholar initiatives that enrich the postdoctoral experience at Stanford. SPIF will consider a broad range of projects, and funding is targeted towards groups mostly specific to Postdoctoral Scholar affairs. Postdoctoral Scholars must be significantly involved in the organization of acceptable initiatives. In principle, any group can be considered for funding if the projects are organized mainly by and for Postdoctoral Scholars.

B.  The rules of operation are described in the general guidelines of SPIF.

C.  The chair of SPIF regularly reports to the **Treasurer/Financial Officer** about approved proposals, and the amount of funding that is awarded, and monthly to the Council about their progress. 

D.  The annual operating budget of SPIF shall be set and agreed upon by the Council as part of the Treasurer’s/Financial Officer’s budget proposal for the upcoming year ([Article III Section 5B](#article-iii-executive-branch)).

--

#### Section 7: Postdoc Representative Seats

A.  SURPAS has a voting seat on the Faculty Senate Committee on Library (C-LIB), Faculty Senate Committee on Academic Computing and Information Systems (C-ACIS), and Faculty Senate Committee on Research (C-RES). These prestigious seats must be filled by May-June to be effective by September of the same year and are elected by Council.

B.  The **Co-Chairs** are granted two non-voting seats on the Faculty Senate for the School of Medicine, but in the instance that one or both **Co-Chairs** do not come from the School of Medicine another SURPAS member may be appointed (at least one of the two seats should be occupied by a member of the Leadership Team).

C.  SURPAS has one voting seat on the School of Medicine Diversity Cabinet that can be filled by appointment of a member of the Council or the Leadership Team.

D.  The **Co-Chairs** are granted one non-voting seat on the University Faculty Senate.

E.  The **Co-Chairs** have two non-voting seats on the Provost Advisory Council on Postdoctoral Affairs (PACPA).

F.  SURPAS representatives to these Committees, Cabinets, and Senates will uphold these Bylaws and represent to their best ability the interests of the Council and all Postdoctoral Scholars at Stanford. They will provide any updates to the Council of pertinent information if possible at the monthly Council meeting.

--

#### Section 8: Special Advisors to the Council

Former Council officers who remain in good standing with the Council have the option to become Special Advisors following their term in office. Special Advisors provide continuity from one Council administration to the next, and provide advice to the Council and Leadership Team as needed. They may be nominated by the **Co-Chairs**, Leadership Team, or Council for a one year term (with the option for renewal at the end of the term).

--

#### Section 9: Leave of Absence from Council

A council member shall be permitted to take a leave of absence from SURPAS Council during parental/baby bonding leave, for physical or mental health reasons, family matters, or other extenuating circumstances. A council member on leave shall retain their position on council upon their return, but their seat is not counted towards quorum during their period of absence. The Council can appoint a substitute to serve on any committees or in any position that requires attendance while the council member is away on leave; however, the council member will resume all of these positions once he or she is back from leave. Notice for a leave of absence should be submitted to the **Co-Chairs** and the **Operations Manager**, should define the estimated period of absence (start and end dates), and identify any positions that would require a substitute during this absence (such requests do not require a vote of approval from Council or Leadership).

---

### Article III: Executive Branch

#### Section 1: Membership of Executive Branch (Leadership Team)

A.  All members of the Council are eligible to run for vacant Leadership Team seats.

B.  The Leadership Team consists of two **Co-Chairs**, an **Events Coordinator**, an **Advocacy Coordinator**, a **Financial Officer**, an **Operations Manager**, a **Community Engagement Liaison**, a **Social Media and Web Manager**, and a **Communications Manager**.

C.  In the event that a position on the Leadership Team cannot be filled, the **Co-Chairs** must take on the responsibilities of that role until a nominee is found or delegate the tasks to a member of the Leadership Team or Council. If either or both of the Co-Chair positions cannot be filled, the Events and Advocacy Coordinators will share the extra responsibilities and may delegate additional responsibilities among Leadership and Council. Significant decisions should be discussed and approved by a simple majority vote of Council.

D.  The Leadership Team shall be in charge of the Council and make sure the Council decisions are executed. The Leadership Team shall have those powers and responsibilities listed in these Bylaws. Unless otherwise specified, all Leadership Team decisions shall be made by consensus.

E.  The Leadership Team shall have the power to create committees of the Council and have oversight of these Committees, shared among the members of Leadership. The structure of this oversight will be determined each year by the Leadership team following review of the annual Committee Project Plans ([Article II, Section 5](#article-ii-legislative-branch)).

F.  The Leadership Team has the discretionary power to handle incoming requests from SURPAS members or outsiders. They shall inform the Council of such decisions, or approach the Council when uncertain how to handle them.

G.  The Leadership Team shall ensure that the following information is available to all members of SURPAS: the Reimbursement procedures, these Bylaws, the approved minutes of Council meetings, the names and titles of all elected and appointed Council members. Any proprietary business information or employee information related to Stanford Student Enterprises shall not be made available to anyone other than the **Co-Chairs** or members of the Council without the consent of the Office of Postdoctoral Affairs or its designee.

--

#### Section 2: Responsibilities: Co-Chairs

A.  Oversee the operations of the Council and SURPAS Committees. This includes coordinating with the **Treasurer/Financial Officer** and **Operations Manager** to produce the Association Annual Report, the financial statement and budget proposal (Article III Section 5B) and to schedule, set the agenda ([Article III Section 6B](#article-iii-executive-branch)), and facilitate Council and Leadership meetings.

B.  Serve as the primary contact for Stanford Administration. One of the **Co-Chairs** shall be listed as President and the other as Co-President on OrgSync, which does not recognize the term Co-Chair. The **Co-Chairs** serve as the liaisons to postdoctoral Associations at other Universities, especially at the annual meeting of the National Postdoctoral Association in March. They represent SURPAS at the quarterly Postdoctoral Scholar orientation sessions hosted by the Office of Postdoctoral Affairs (OPA), and represent SURPAS as ex officio members of the Provost Advisory Committee on Postdoctoral Affairs (PACPA) and the Faculty Senate of the School of Medicine ([Article II Section 7B](#article-ii-legislative-branch)).

C.  Oversee the timely appointment and/or election of new members and notification of vacancies on the Council to the community at large.

D.  Conduct and report an annual or biannual survey on the state of postdoctoral life with the Office of Postdoctoral Affairs.

E.  Outline the current status of SURPAS and summarize its goals for the upcoming year in an address to the Council, to be given between August and September.

F.  The **Co-Chairs** may delegate any of these duties to other members of the Leadership, the Council or SURPAS.

G.  **Co-Chairs** should schedule quarterly meetings with OPA and Affinity group co-chairs

--

#### Section 3: Responsibilities: Events Coordinator

A.  Work closely with SURPAS committees and committee chairs to establish a workflow for organizing events.

B.  Keep an updated list of volunteers (from the Council and outside members) and work to recruit more volunteers; ensure participation of SURPAS Council in the quarterly Postdoctoral Scholar orientation sessions hosted by OPA.

C.  Make and maintain contact with other postdoc associations at Stanford to organize events during National Postdoc Appreciation Week (NPAW) or at any other time during the year.

D.  Schedule or coordinate events on a monthly basis, checking for any coinciding event with OPA or other postdoc associations at Stanford.

E.  Work with the Co-chairs to plan events, the Communications Manager and Social Media and Web Manager for advertising, and the **Treasurer/Financial Officer** to determine  allocated budget for each event.

F.  Outline and maintain a tentative yearly calendar of SURPAS events, including annual events(Wellness Fair, NPAW, Symposium) and monthly events (Happy Hours, Coffee Chats) for the Council’s reference.

--

#### Section 4: Responsibilities: Advocacy Coordinator

A.  Work closely to gather data to facilitate identification of the postdoc problems informally(anecdotal) or formally (survey).

B.  Work with data from survey on postdoc value from the OPA ([Article III Section 2D](#article-iii-executive-branch)).

C.  Keep an updated list of Special Advisors to the council ([Article II Section 8](#article-ii-legislative-branch)) and identify allies in the faculty/administration (in addition to the Advisory Board - [Article VII Section 2](#article-vii-review-and-conflict-resolution)).

D.  Be informed about all the administrative committees and faculty senate committees and advise **Co-Chairs** concerning proposals to the PACPA and faculty senates.

E.  Coordinate efforts to gain more visibility for postdoc work/value across campus (i.e., features on Stanford Daily newspaper, etc.).

F.  Coordinate outreach and advocacy efforts with other communities on campus (i.e., graduate and undergraduate students, other postdoc groups at Stanford).

G.  Create and maintain a general workflow for directing advocacy efforts, updated at least annually by each outgoing Advocacy Coordinator.

H.  Work jointly with the **Operations Manager** to hold a short orientation for newly elected members of the Council at least quarterly.

--

#### Section 5: Responsibilities: Treasurer/Financial Officer

A.  Manage the SURPAS budget and act as a liaison with the Office of Postdoctoral Affairs (OPA) for financial matters. The **Treasurer/Financial Officer** is responsible for financial oversight, compliance and disbursement, in accordance with the approved budget allocation limits and University policy. The **Treasurer/Financial Officer** must complete the ASSU Banking training session, before receiving authority to manage the ASSU account, and ensure that at least one Co-Chair has also completed the training to act as co-signer in cases when the **Treasurer/Financial Officer** must be reimbursed.

B.  Draft, negotiate (with the **Co-Chairs**), and present (with the **Co-Chairs**) an annual budget proposal to the Associate Dean for Postdoctoral Affairs, due March 1st. The **Treasurer/Financial Officer** will report the approved budget to the Council at the next Council meeting.

C.  Present annually to the Council the financial statement of the previous year and the budget proposal annually prior to evaluation by leadership and submission to the OPA ([Article III Section 5B](#article-iii-executive-branch)). The Council shall approve these documents by majority vote. 

D.  Prepare a quarterly financial report of revenues and expenses of the account to the Council, which the **Co-Chairs** can present to the Associate Dean for Postdoctoral Affairs upon request.

E.  All monthly financial transactions shall be completed within SURPAS for each month prior to the 1st of the next month.

--

#### Section 6: Responsibilities: Operations Manager

A.  Record minutes at each Council and Leadership Team meeting. Distribute minutes to Leadership Team and Council members prior to the next council meeting. Obtain approval of the Council meeting minutes from the Leadership Team, prior to distributing them to the Council as draft minutes. Ensure that approved minutes become generally accessible.

B.  Create the Council meeting agenda document for dissemination to Council members during the Leadership meeting with input and assistance from the **Co-Chairs** and Leadership Team.

C.  Organize, handle and coordinate SURPAS documents, including a record of Council meeting attendance. Refer to the Bylaws at elections. Schedule rooms and/or zoom meetings for Leadership Team and Council meetings. Handle letters of appointment and welcome packet for new members of the Council and Leadership Team. These letters shall be signed by **Operations Manager** and **Co-Chairs** and can be sent electronically.

D.  Ensure that voting is accessible to all council members (ie. all members have access to a phone or a computer if voting electronically or ballots, and writing utensils if voting by paper

E.  Tabulate votes and report voting totals to the **Co-Chairs** and ensure that the **Co-Chairs** report voting results during the meeting in which voting took place.

F.  Work jointly with the **Advocacy Coordinator** to lead short orientations for new council members at least quarterly. This includes providing new members with the welcome packet and providing new members with avenues to volunteer their time as Council members.

G.  Ensure that information from Council meetings is communicated to all Postdoctoral Scholars. This includes, but is not limited to providing the Social Media and Web Manager with documents to post on the website and sending approved minutes by email to the listserv.

H.  Review and update Bylaws in consultation with the Leadership Team annually in December or January ([Article VII Section 4A](#article-vii-review-and-conflict-resolution)).

--

#### Section 7: Responsibilities: Social Media and Web Manager

A.  Manage outgoing communications from the Leadership Team, specifically through the SURPAS social media accounts and website.

B.  Communicate information, events, and news related to the activities of the Council and SURPAS, in concordance with the **Communications Manager**. (See [Article VIII, Section 4](#article-viii-external-communications) for additional details)

C.  Maintain the SURPAS website. To this end, the Social Media and Web Manager will update the Leadership Team and Council members’ contact information and member profiles, maintain an agenda of activities, post important documents and photographs of events and keep the website up-to-date by adding new information and removing dated information.

D.  The Social Media and Web Manager will also pay the website renewal fee and request reimbursement from the **Treasurer/Financial Officer**.

E.  Update and maintain the SURPAS website and social media accounts (including Facebook, Twitter, Instagram, etc.).

F.  Coordinate event listings and advertising with the **Events Coordinator** and **Communications Manager**.

G.  It is the responsibility of the **Social Media and Web Manager**, **Communications Manager**, and the **Co-Chairs** to ensure that all Stanford postdocs are informed of any important current affairs relevant to postdoctoral scholars at Stanford.

--

#### Section 8: Responsibilities: Communications Manager

A.  Manage the outgoing communications of the Leadership Team, specifically through email. The Leadership Team will communicate to the postdoctoral community from a centralized mailing account (surpas-announcements@lists.stanford.edu). All active leadership team members will receive access to this account. Outgoing mail will be signed on behalf of the leadership team as “SURPAS”.

B.  Communicate to the public, in concordance with the **Social Media and Web Manager**, information, events, and news related to the activities of the Council and SURPAS. (See [Article VIII, Section 4](#article-viii-external-communications) for additional details)

C.  Coordinate event listings and advertising (including printing and posting banners, flyers, etc. and electronic communications) with the **Events Coordinator** and **Social Media and Web Manager**.

D.  Oversee all official outgoing email communications of the Leadership Team and the Council by managing the common email account and the email lists of SURPAS. Management entails ensuring timely and accurate replies to incoming emails by notifying responsible officers or via a meeting agenda item. The Communications Officer may reply in order to acknowledge the incoming email was received.

E.  It is the responsibility of the Communications Manager, Social Media and Web Manager, and the **Co-Chairs** to ensure that all Stanford postdocs are up to date with any important current affairs relevant to postdoctoral scholars at Stanford.

--

#### Section 9: Community Engagement Liaison

Note: This position is being created on a temporary basis and will be evaluated at 6 months and following the first 1 year appointment to determine whether it should be renewed going forward. (created 2019 session)

A.  Postdocs interested in obtaining SURPAS sponsorship for an event will work with the **Community Engagement Liaison** to help them meet all applicable rules and regulations.

B.  Be informed regarding SURPAS and Stanford policies regarding on campus events and update Council of any relevant changes or new policies.

C.  Coordinate the development of yearly SURPAS policies regarding Committee oversight and oversee an annual meeting of Committee representatives to discuss these and Stanford policies.

D.  Serve as the official representative of SURPAS to other postdoc groups as well as postdocs at large regarding SURPAS policies.

E.  Serve as the official SURPAS representative to the OSE and ASSU.

F.  Work with the **Events Coordinator** to optimize logistics for SURPAS sponsored events.

G.  Coordinate information exchange between Postdoc Representative Seats, the Leadership Team, and Council.

H.  Work with the Leadership team and Council to develop policies for postdoc community outreach.

--

#### Section 10: Term Expiration

A.  Appointments to the Leadership Team are for one year, confirmed by a letter of appointment.

B.  A position in the Executive Branch of SURPAS shall become vacant upon resignation or disqualification. A member of the Executive Branch can resign by submission to the Council of a written statement of resignation. Any member of the Council may call for a vote of disqualification from the Council or Leadership Team and this must be seconded by a member of Leadership. The individual will be notified of the call for disqualification and the vote will occur at the next earliest Council meeting. Disqualification would occur with a two-thirds vote by Council.

C.  No Council member can hold more than one Leadership position simultaneously; officers who are nominated and run for a second position on the Leadership team must resign from their previous position immediately upon election.

---

### Article IV: Guidelines for Committee Meetings

#### Section 1: General

For the purpose of this section, Committee refers to Committees as well as the Leadership Team. Committees shall assign a chair or co-chairs and an **Operations Manager** (as needed) from among their members.

A.  Committee members may meet in Committee meetings whenever needed.

    1.  Committee meetings are led by the designated chair(s) who determine(s) the agenda upon gathering input from all members. The agenda with accompanying documentation shall be distributed prior to the meeting.

    2.  The co-chairs or operations manager shall take notes during the meeting, and distribute the draft minutes within seven days after the meeting among the members. All members shall provide their feedback, and the final version shall be voted during the next meeting.

    3.  Meetings can take place in person or via web-based communication platforms (Eg: Skype/zoom) and can be rescheduled when multiple Committee members indicate in advance that they cannot attend. It is recommended that Committees meet in preparation of Council meetings.

B.  Decisions taken at Committee meetings are based on consensus and must be supported by all active members present.

    1.  If opposing views exist the Committee is advised to defer the decision and look for a solution backed by all.

    2.  If no resolution can be reached among members, committees can appeal to SURPAS Council or Leadership for advice and resolution.

C.  Decisions are preferably taken during face-to-face meetings, either in person or via a web-based communication platform (Skype, Webex, Zoom, etc.).

    1.  If rapid action is required and a face-to-face meeting is not possible, the responsible member shall notify each member prior to action.

    2.  Committee members may vote per email, with regards to Committee decisions.

    3.  Committee members may vote per web tool, with regards to Committee decisions.

    4.  All active Committee members have one vote each.
    
    5.  Committee members cannot vote on behalf of absent members.

D.  Committees may defer the rules stated in [Article IV Section 1B](#article-iv-guidelines-for-committee-meetings) and [Article IV Section 1C](#article-iv-guidelines-for-committee-meetings) in extreme cases, such as prolonged leave of absence ([Article II, Section 9](#article-ii-legislative-branch)). Should this occur, outward communication will state that the decision was not unanimous, the minutes will explain the extraordinary situation, and the reason shall be shared with all active Committee members. Moreover an active solution must be sought ([Article IV Section 1B2](#article-iv-guidelines-for-committee-meetings)).

---

### Article V: Elections

#### Section 1: General

A.  SURPAS holds Council and Officer elections.

B.  Council elections shall occur when there are vacant Council seats. Officer elections shall occur in January for one of the two **Co-Chair** positions and the **Community Engagement Liaison** and June/July for the other **Co-Chair** position and rest of the Leadership Team. The positions will be effective by February or August of the same year depending on when the election occurred. All elections shall be held during a regular Council meeting.

C.  In the case that an officer position becomes vacant mid-term, elections for that position shall be called within one month to create an interim officer.

D.  The positions shall be advertised to all SURPAS members and then selected by majority vote of the Council at an advertised Council meeting. All posts will be held for one year. Council members and officers may run for consecutive terms.

E.  The **Co-Chairs** shall present the election results to the Council, SURPAS, and Office of Postdoctoral Affairs.

--

#### Section 2: Campaign Regulations

A.  Postdoctoral Scholars who are interested in running for a Council position shall notify the **Co-Chairs** or the **Operations Manager**.

B.  Eligible Postdoctoral Scholars shall have attended at least one prior Council meetings.

C.  Council members interested in running for an officer position shall notify the **Co-Chairs** or the **Operations Manager**.

D.  Candidates shall submit a written statement to the **Co-Chairs** so that it can be shared with the Council members and Leadership Team prior to voting.

E.  The **Co-Chairs** shall share the names of candidates with the Council prior to elections.

--

#### Section 3: Voting

A.  Voting shall occur only at Council meetings, where each Council member present shall carry one vote. Results depend on a majority and the rules of quorum.

B.  In the case of a tie, elections are adjourned and the Council shall call for runoff elections.

--

#### Section 4: Invalidation of Election Results

The Council shall have power to invalidate the results of an election if the election was not done in accordance with the Bylaws.

---

### Article VI: Finances

#### Section 1: General

A.  The **Treasurer/Financial Officer** shall maintain all financial records and distribute the budget proposal and budget among the Leadership Team and the Council ([Article III Section 6B](#article-iii-executive-branch)).

B.  Any Council member may request insight into financial documentation by approaching the **Co-Chairs** or **Treasurer/Financial Officer**.

C.  The fiscal year of SURPAS shall begin on July 1 and end on June 30.

--

#### Section 2: SURPAS Operating Budget

A.  No funds shall be expended, encumbered, or otherwise disbursed by SURPAS other than in accordance with the procedures for the authorization of expenditures or investments contained in these Bylaws.

B.  All funds expended by SURPAS shall be used for the basic operating expenses of SURPAS, or for programs initiated by and under the control of SURPAS and its agencies (including SPIF and requests from the Office of Postdoctoral Affairs).

C.  No funds shall be expended as salaries or wages by any SURPAS member, department or agency.

D.  The allocated SURPAS budget may be deposited in an account with the Capitol Group banking services of the Stanford Student Enterprises (SSE), a division of the ASSU or with SURPAS’ PTA, under the authority of the Office of Postdoctoral Affairs.

E.  The Associate Dean for Postdoctoral Affairs will serve to oversee the accounts and holds authority to close them in case of financial malfeasance or non-compliance on the part of the Leadership Team or Council. The Associate Dean for Postdoctoral Affairs will facilitate any necessary mediation of disputes or problems regarding this account.

F.  Events and activities charged to the SURPAS accounts must comply with University Event Planning and Alcohol Policies as well as other applicable funding policies that pertain to student groups at Stanford, including those on sponsorships, unless a written authorization for a policy exception is received by the **Treasurer/Financial Officer** from the Associate Dean for Postdoctoral Affairs.

G.  At the end of the funding period (annually), unspent funds in the account may be carried forward to the next fiscal period upon discussion and approval of the following year’s budget proposal with the Associate Dean for Postdoctoral Affairs, with the exception of funds designated to sponsor major events, which must be returned to the sponsors if unspent.

H.  Any funds specifically deposited in one funding period (e.g., University fiscal year) for an event in a later funding period (e.g., the subsequent University fiscal year) may be automatically rolled-over. The **Treasurer/Financial Officer** will confirm the roll-over ahead of time.

---

### Article VII: Review and Conflict Resolution

#### Section 1: Conflict Resolution

A.  It is the policy of SURPAS to provide Postdoctoral Scholars with an opportunity to resolve disputes in a fair and collegial manner. These guidelines establish a formal process for SURPAS members, including council members and officers, to request, review and redress certain disputes arising out of their relationships within SURPAS. This section does not deal with conflict between Postdoctoral Scholars and their PIs or colleagues.

B.  Conflicts that cannot be resolved at local level should be brought to the attention of the **Co-Chairs**. The **Co-Chairs** will listen to the complaints and hear everyone involved. They should attempt to achieve a satisfactory solution by referring to these Bylaws. The **Co-Chairs** may seek advice from the Associate Dean for Postdoctoral Affairs.

C.  For disagreements that remain unresolved after the **Co-Chairs** are consulted, a grievance process will be initiated when the SURPAS member files a written grievance with the **Co-Chairs**. The parties in the grievance process shall be the person(s) filing the grievance and the person(s) responsible for the act or omission that gave rise to the grievance.

D.  In response to the written grievance, the **Co-Chairs** will seek advice from the Advisory Board. Should the dispute involve the **Co-Chairs**, Council members may approach the Advisory Board directly.

E.  The advice from the Advisory Board will be communicated to the Council¸ which will formally decide how to implement the advice.

--

#### Section 2: Advisory Board

A.  The purpose of the Advisory Board is to provide advice to the **Co-Chairs** and Council and thereby help them navigate through unforeseen situations which are not adequately covered by these Bylaws.

B.  Membership & Member Qualifications:

    1.  The Advisory Board shall consist of three members, ideally:

        i.  The Associate Dean for Postdoctoral Affairs

        ii.  The Senior Associate Dean of Graduate Education and Postdoctoral Affairs (School of Medicine) 

        iii. The Vice Provost for Graduate Education.

    2.  Membership shall be recruited from Stanford staff and faculty, who are impartial to Postdoctoral Scholars.

    3.  The **Co-Chairs** of the Council organize the invitations to serve on the Advisory Board if they cannot be filled from the three positions listed above. Nominations will be discussed with and approved by the Council.

    4.  Advisory Board members agree to serve for two years, open to renewal.

    5.  Advisory Board membership is a volunteer role without compensation.

    6.  Advisory board members shall notify the **Co-Chairs** when they are no longer able to execute their functions, whereupon the **Co-Chairs** shall seek replacements.

    7.  Advisory Board members shall have experience with postdoctoral affairs, conflict resolution, or rules of conduct.

C.  Operation:

    1.  The **Co-Chairs** of the Council will approach the Advisory Board with a written statement of grievance filed by the complainant, as well as a written account of attempts at reconciliation. The Board shall review the conflict and issue advice on future actions. Review may include meeting with the Postdoctoral Scholars involved, or soliciting feedback. The advice shall be two-fold:

        i.  Advice aimed at helping the Council resolve the current conflict.

        ii.  Advice aimed at preventing similar grievance from occurring again.

    2.  The Advisory Board is free to decide its mode of operation, but will communicate a timeline to the **Co-Chairs** upon receipt of the request.

    3.  The **Co-Chairs** will provide an annual update of affairs to the Advisory Board. SURPAS Bylaws 16

--

#### Section 3: The Untimely Removal of an Appointed Officer

A.  For the purpose of this guideline, an "appointed officer" shall be taken to mean any position whose occupant must be approved by the Council.

B.  Appointed Officers can be removed by the Council for failure to execute their responsibilities. Any individual or Committee subject to possible disciplinary action by the Council must be given written notice of the intended action at least 72 hours before the meeting at which the disciplinary action would be approved, so that they are allowed to speak in defense at the meeting. The council will vote by 2/3 majority.

--

#### Section 4: Review

A.  The Council shall review these Bylaws annually in December and/or January (or as needed) under direction of the **Operations Manager** ([Article III Section 6E](#article-iii-executive-branch)) and Leadership Team or as an ad hoc committee.

B.  The portion of the SURPAS policies that affect the Council may be adopted, amended, or repealed by a 2/3 vote of the Council. Association policies not affecting the Council may be adopted, amended, or repealed by a majority vote of the Council, provided that consultation with the governing body of the affected SURPAS entity has occurred.

C.  Proposed changes to these Bylaws can be made at any time following discussion at a regularly scheduled Council meeting, and should be submitted in writing to the **Co-Chairs** and presented for discussion at the next scheduled Council meeting.

D.  Proposed changes must be submitted to the Council at least two weeks in advance to the Council meeting at which the vote shall occur, to allow for ample time for review.

---

### Article VIII: External Communications

#### Section 1: Announcements on behalf of Council

In the event that a council member(s) wishes to make a statement on behalf of the Council, the member(s) should present the written statement to the Leadership Team. If the Leadership Team reaches consensus that the statement reflects the spirit and/or goals of the Council, they will share the statement with the Council prior to the next meeting. Council will then vote to approve the release of the statement to the Postdoctoral community, passed by simple majority. If the statement requires expedience (cannot or should not wait until the next Council meeting), the Leadership may distribute the statement to the Council electronically with a deadline of at least 24 hours for approval. The statement may be released once a majority of Council members approve.

--

#### Section 2: Communication with the Media

In the event that a Council member(s) are contacted by a member(s) of the media external to the University (journalists, bloggers, etc…) to solicit opinions, it is highly recommended that the member consult with the Office of Postdoctoral Affairs and/or the Office of the Vice Provost for Graduate Education about how to respond. Stanford does not set limitations for interactions with the media. However, Council members are advised to think carefully about the experiences they can speak to and to critically interrogate the motivations of those seeking comment. Any statement made must clearly be the opinion of the individual Council member(s) and not as Council or SURPAS or the Stanford postdoctoral community as a whole without prior approval and consent (as outlined in [Article VIII Section 1](#article-viii-external-communications)).

--

#### Section 3: Interactions with other Postdoc Groups

The Office of Student Engagement (OSE) at Stanford University recognizes SURPAS as the only official postdoctoral organization; however, SURPAS recognizes and works with any other group whose goal is to represent the diverse identities and interests of postdoctoral scholars at Stanford.

--

#### Section 4: Communications during the Fall and Winter Holidays

Thanksgiving is a national holiday that is celebrated widely, most times without thought about the historical context. SURPAS, however, should be thoughtful about what Thanksgiving means both for Indigenous people and traditional family gatherings when messaging around this time. This could be an important opportunity for education about colonial violence and the centering of Indigenous heritage and sovereignty. Similarly, Winter brings a variety of holidays, each unique to their religion of origin and each celebrated by some and not others. Messaging around the Winter Holidays should be done with this in mind.

### Appendices

**Leadership Guide(s) Events Planning Guide**

**Important University Contacts**



