---
title: "Conclusions"
bibliography: 20230324_SURPAS_Long_Range_Planning_refs_edited.bib
csl: nature.csl
---

This Report contextualizes the role of postdocs within academia *as viewed by postdocs themselves*. The national landscape for postdoc employment within the United States and at Stanford specifically was analyzed by drawing from a wide variety of reputable sources in the [Opportunities for Early Career Researchers: Competitive Landscape for Postdocs](competitivelandscape.qmd) section. An overview of previous advocacy efforts performed by organized postdocs at Stanford was provided in the [A Quarter Century of Postdoc Advocacy at Stanford: Review of Previous Work](previouswork.qmd) section. The mindset and goals for postdocs at Stanford in the early 2020s was ascertained in the [Conversations with Postdocs at Stanford: Focus Groups 2021](focusgroups.qmd) section. Models of postdoc advocacy and data about contemporary issues of concern for postdocs are provided in the [Ongoing Postdoc Advocacy at Stanford: Surveys and Letters 2021/2022](ongoingadvocacy.qmd) section. Issues facing postdocs and expectations for how various stakeholders can address them are included in the [Recommendations](recs.qmd) section.

With this Report, SURPAS is positioning postdocs as an important stakeholder within the University and academic research settings. The Report serves as a form of institutional memory for future postdocs at Stanford, crystallizing many efforts and goals undertaken by postdoc organizers in a single document and helping to combat the issues that arise due to the transient nature of the postdoc as it currently exists. The vision for the future of postdocs at Stanford presented within this Report includes data and ideas that future postdoc leaders can leverage. This Report also serves as a communication to other stakeholders within the University and academic communities of postdoc goals and expectations.

The issues, themes, and recommendations within this report are neither groundbreaking nor unique. Many of the same themes emerged in the Fall 2022 survey of postdocs conducted by the National Postdoc Association.[@k6g] The issues and recommended solutions echo calls made by researchers at various levels of the academic research enterprise for more than two decades. The COVID-19 pandemic revealed and exacerbated many existing trends, but these inequities are longstanding.

Postdocs at Stanford are relatively better resourced and organized compared with postdocs at other institutions but still face many challenges. It is the hope of the Committee that the materials contained within this Report can serve as a model for postdocs at other institutions to adapt to their own local conditions. Though Stanford employs a disproportionate share of postdocs compared with most other institutions in this country, the nearly 2500 postdocs at Stanford represent a small fraction of postdocs in the US. Additional data about the material conditions of postdocs at a wider variety of institutions will help provide a more complete picture of postdoc positionality.
