---
title: "Table of Contents"

---


* [Acknowledgements](acknowledgements.qmd)
  + [SURPAS Long Range Planning Committee Members (2020-23)](acknowledgements.qmd#surpas-long-range-planning-committee-members-(2020-23))
  + [Contributors](acknowledgements.qmd#contributors)
  + [Land Acknowledgement](acknowledgements.qmd#land-acknowledgement)	
* [EXECUTIVE SUMMARY](execsumm.qmd)	
* [Contents](contents.qmd)
* [Purpose, Mission, & Process for SURPAS Long Range Planning](purpose.qmd)	
* [Postdoc at Stanford Background](background.qmd)	
  + [Defining a “Postdoc”](background.qmd#defining-a-“postdoc”)	
  + [Postdoc Demographics at Stanford](background.qmd#postdoc-demographics-at-stanford)
* [Opportunities for Early Career Researchers: Competitive Landscape for Postdocs](competitivelandscape.qmd)
  + [Introduction](competitivelandscape.qmd#introduction)	
  + [Postdocs in the US](competitivelandscape.qmd#postdocs-in-the-us)	
    - [Changing Workforce Demographics](competitivelandscape.qmd#changing-workforce-demographics)	
    - [Higher Education Does Not Mean Higher Pay](competitivelandscape.qmd#higher-education-does-not-mean-higher-pay)	
    - [Advanced Training for Limited Academic Roles](competitivelandscape.qmd#advanced-training-for-limited-academic-roles)	
  + [Postdocs at Stanford](competitivelandscape.qmd#postdocs-at-stanford)	
    - [Prestige Does Not Prevent Poverty](competitivelandscape.qmd#prestige-does-not-prevent-poverty)	
    - [The Reality of Postdoc Financial Challenges](competitivelandscape.qmd#the-reality-of-postdoc-financial-challenges)	
    - [Representation and Advocacy on Campus](competitivelandscape.qmd#representation-and-advocacy-on-campus)	
  + [Conclusion](competitivelandscape.qmd#conclusion)	
* [A Quarter Century of Postdoc Advocacy at Stanford: Review of Previous Work](previouswork.qmd)	
  + [Overview](previouswork.qmd#overview)	
  + [Theme 1: Mentoring](previouswork.qmd#theme-1-mentoring)	
  + [Theme 2: Affordability](previouswork.qmd#theme-2-affordability)	
  + [Theme 3: Status](previouswork.qmd#theme-3-status)	
  + [Theme 4: Justice, Diversity, Equity, Inclusion, Belonging](previouswork.qmd#theme-4-justice-diversity-equity-inclusion-belonging)	
  + [Theme 5: Implementation & Outreach](previouswork.qmd#theme-5-implementation--outreach)	
* [Conversations with Postdocs at Stanford: Focus Groups 2021](focusgroups.qmd)	
  + [Overview](focusgroups.qmd#overview)	
  + [Meta-Analysis of Focus Group Conversations](focusgroups.qmd#meta-analysis-of-focus-group-conversations)	
  + [Postdoc Salaries Are Insufficient For Extremely High Cost of Living](focusgroups.qmd#postdoc-salaries-are-insufficient-for-extremely-high-cost-of-living)	
  + [Postdoc Parents Face Very High Costs and Low Access to Childcare](focusgroups.qmd#postdoc-parents-face-very-high-costs-and-low-access-to-childcare)	
  + [Strong Research Environment and Vibrant Postdoc Community at Stanford](focusgroups.qmd#strong-research-environment-and-vibrant-postdoc-community-at-stanford)	
  + [Instability of Postdoc Position Prevents Longer-Term Life Planning](focusgroups.qmd#instability-of-postdoc-position-prevents-longer-term-life-planning)	
  + [Effective Formal Postdoc Structure Is Lacking](focusgroups.qmd#effective-formal-postdoc-structure-is-lacking)	
  + [US Funding Systems Difficult to Navigate, Especially for International Postdocs](focusgroups.qmd#us-funding-systems-difficult-to-navigate-especially-for-international-postdocs)	
  + [Ambiguous Status of Postdocs on Campus Leads to Feelings of Exclusion](focusgroups.qmd#ambiguous-status-of-postdocs-on-campus-leads-to-feelings-of-exclusion)
  + [Much More Effort is Required on Justice, Diversity, Equity, Inclusion, & Belonging](focusgroups.qmd#much-more-effort-is-required-on-justice-diversity-equity-inclusion--belonging)	
  + [Existing Academic Incentive Structures are Poorly Designed & Unclear](focusgroups.qmd#existing-academic-incentive-structures-are-poorly-designed--unclear)	
  + [Postdocs are Not Always Aware of the Resources that are Available to Them](focusgroups.qmd#postdocs-are-not-always-aware-of-the-resources-that-are-available-to-them)	
* [Ongoing Postdoc Advocacy at Stanford: Surveys & Letters 2021/2022](ongoingadvocacy.qmd)	
  + [Matters Arising from Report Draft (2023)](ongoingadvocacy.qmd#matters-arising-from-report-draft-(2023))	
    - [Meta-Analysis of Feedback on Report Draft](ongoingadvocacy.qmd#meta-analysis-of-feedback-on-report-draft)	
    - [Postdocs are Valuable to the University & Research Enterprise](ongoingadvocacy.qmd#postdocs-are-valuable-to-the-university--research-enterprise)	
    - [Where are the Numbers to Back This Up?](ongoingadvocacy.qmd#where-are-the-numbers-to-back-this-up)	
    - [What is the Specific Salary Ask of the Report?](ongoingadvocacy.qmd#what-is-the-specific-salary-ask-of-the-report)	
    - [Should There be a Time Limit for the Postdoc Period?](ongoingadvocacy.qmd#should-there-be-a-time-limit-for-the-postdoc-period)	
    - [How to Best Define a Postdoc?](ongoingadvocacy.qmd#how-to-best-define-a-postdoc)	
    - [Existing Demographic Data are Inadequate](ongoingadvocacy.qmd#existing-demographic-data-are-inadequate)	
    - [The Question of Postdoc Unionization](ongoingadvocacy.qmd#the-question-of-postdoc-unionization)	
    - [Covering Basic Needs](ongoingadvocacy.qmd#covering-basic-needs)	
  + [SURPAS Leadership Position Paper on Support for the Underrepresented Postdoc Community (2022)](ongoingadvocacy.qmd#surpas-leadership-position-paper-on-support-for-the-underrepresented-postdoc-community-(2022))	
    - Open Letter	
    - Background information	
  + [Stanford Latinx Postdoc Association Survey (Fall 2022)](ongoingadvocacy.qmd#stanford-latinx-postdoc-association-survey-(fall-2022))	
    - Summary of Major Findings	
    - Open Letter	
  + [Stanford Chinese Postdoc Association Housing Costs Letter (2022)](ongoingadvocacy.qmd#stanford-chinese-postdoc-association-housing-costs-letter-(2022))	
  + [SURPAS Benefits and Affordability Survey (Winter 2021/22)](ongoingadvocacy.qmd#surpas-benefits-and-affordability-survey-(winter-202122))	
    - Demographics	
    - Summary of Results	
    - Recommendations	
  + [SURPAS Family Committee Letter (2020/21)](ongoingadvocacy.qmd#surpas-family-committee-letter-(202021)))	
    - Letter	
    - Testimonials	
* [RECOMMENDATIONS](recs.qmd)
  + [Overview](recs.qmd#overview)	
  + [Costs: Overall](recs.qmd#costs-overall)	
  + [Costs: Food Insecurity](recs.qmd#costs-food-insecurity)	
  + [Costs: Housing](recs.qmd#costs-housing)	
  + [Costs: Transition to Postdoc](recs.qmd#costs-transition-to-postdoc)	
  + [Costs: Childcare](recs.qmd#costs-childcare)	
  + [Costs: Healthcare for Dependents](recs.qmd#costs-healthcare-for-dependents)	
  + [Justice, Diversity, Equity, Inclusion, Belonging](recs.qmd#justice-diversity-equity-inclusion-and-belonging)	
  + [Mentorship & Formal Structure](recs.qmd#mentorship--formal-structure)	
  + [Building Community](recs.qmd#building-community)	
  + [Postdoc Visibility](recs.qmd#postdoc-visibility)	
  + [Postdoc Status](recs.qmd#postdoc-status)	
  + [Insecurity: Job](recs.qmd#insecurity-job)	
  + [Insecurity: Immigration](recs.qmd#insecurity-immigration)	
  + [Career Tracking & Job Seeking](recs.qmd#career-tracking--job-seeking)	
  + [Incentives in Academia](recs.qmd#incentives-in-academia)	
  + [Orientation & Onboarding](recs.qmd#orientation--communication)
  + [Personal Health & Safety](recs.qmd#personal-health--safety)
  + [Language in Communication](recs.qmd#language-in-communication)
* [Conclusions](conclusions.qmd)
* [Bibliography](biblio.qmd)
* Appendices
  + [Appendix A: SURPAS (Stanford Postdoc Association) By-Laws](appendixa.qmd)
  + [Appendix B: How to Run a Long Range Planning Focus Group](appendixb.qmd)
  + [Appendix C: Communication Strategy of Report](appendixc.qmd)
  + [Appendix D: Data Tables](appendixd.qmd)
